import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlinx-serialization'
    id 'org.jetbrains.kotlin.kapt'
    id 'org.jetbrains.kotlin.plugin.compose' version '2.3.20'
}

android {
    namespace 'com.ca.insulinreminder'
    compileSdk gradleDependencies.compileSdk

    defaultConfig {
        minSdk gradleDependencies.minSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
        }
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion kotlinCompilerExtensionVersion
    }
}

dependencies {
    implementation project(":core:designsystem")
    implementation project(":core:common")
    implementation project(':core:alarmscheduler')
    compileOnly project(":core:database")
    implementation project(":core:datastore")
    implementation project(':core:domain')
    implementation project(':core:model')
    implementation project(':core:data')

    // Android X
    implementation androidxDependencies.coreKtx
    implementation androidxDependencies.lifecycleRuntime
    implementation androidxDependencies.viewModel
    implementation androidxDependencies.dataStore

    // Jetpack Compose
    implementation composeDependencies.ui
    implementation composeDependencies.uiTooling
    implementation composeDependencies.uiToolingPreview
    implementation composeDependencies.material3
    implementation composeDependencies.runtime
    implementation composeDependencies.foundation
    implementation composeDependencies.foundationLayout
    implementation composeDependencies.activity
    implementation composeDependencies.viewModel
    implementation composeDependencies.navigation
    implementation composeDependencies.constraintLayout
    implementation composeDependencies.lifecycleRuntime
    implementation composeDependencies.material3

    // Hilt
    implementation hiltDependencies.hilt
    implementation hiltDependencies.navigationCompose
    kapt hiltDependencies.compiler

    // Room
    implementation roomDependencies.runtime

    //Test
    implementation testDependencies.junit
    implementation testDependencies.espresso

    //Serialization
    implementation serialization.serialization
}