pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "DiabetesDiary"

include ':app'
include ':core:network'
include ':core:designsystem'
include ':core:authentication'
include ':core:datastore'
include ':core:schema'
include ':core:domain'
include ':core:data'
include ':core:model'
include ':core:common'
include ':core:alarmscheduler'
include ':core:database'
include ':core:notification'

include ':features:recordinsulin'
include ':features:recordglucose'
include ':features:settings'
include ':features:home'
include ':features:onboarding'
include ':features:authentication'
include ':features:records'
include ':features:reminders'
include ':features:insulinreminder'
include ':features:glucosereminder'

include ':features:bottomsheet:editglucoserecord'
include ':features:bottomsheet:editinsulinrecord'
include ':features:bottomsheet:editinsulinreminder'
include ':features:bottomsheet:editglucosereminder'
include ':core:navigation'
