import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
}

android {
    namespace 'com.ca.authentication'
    compileSdk gradleDependencies.compileSdk

    defaultConfig {
        minSdk gradleDependencies.minSdk

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        debug{
            buildConfigField('String', 'GOOGLE_CLIENT_ID', GOOGLE_CLIENT_ID)
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField('String', 'GOOGLE_CLIENT_ID', GOOGLE_CLIENT_ID)
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
        }
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {

    implementation project(':core:datastore')

    // Jetpack Compose
    implementation composeDependencies.activity

    // Play Services
    implementation playServicesDependencies.auth

    // DataStore
    implementation androidxDependencies.dataStore

    // Hilt
    implementation hiltDependencies.hilt
    kapt hiltDependencies.compiler

    // Firebase
    implementation firebaseDependencies.bom
    implementation firebaseDependencies.analytics
    implementation firebaseDependencies.crashlytics
    implementation firebaseDependencies.auth

    //Test
    implementation testDependencies.junit
    implementation testDependencies.espresso
}